## Lesson 01 Pandas

In [1]:
import numpy as np
import  pandas as pd

In [2]:
# Series: Population by Country Code
country_population = pd.Series(
     data=[61, 46, 11, 65, 10],
    index=["IT", "ES", "GR", "FR", "PO"],
    name="Country Population"
)
country_population
data = {
    "Name": [
         "Avery Bradley", "John Holland", "Jonas Jerebko",
        "Jordan Mickey", "Terry Rozier", "Jared Sullinger", "Evan Turner"
    ],
    "Team": ["Boston Celtics"] * 7,
    "Number": [0.0, 30.0, 8.0, None, 12.0, 7.0, 11.0],
    "Position": ["PG", "SG", "PF", "PF", "PG", "C", "SG"],
    "Age": [25.0, 27.0, 29.0, 21.0, 22.0, None, 27.0]
}
df_0 = pd.DataFrame(data)

In [3]:
country_population

IT    61
ES    46
GR    11
FR    65
PO    10
Name: Country Population, dtype: int64

In [4]:
s1 = pd.Series([1,2,3], index = ['a','b','c'])
s1

a    1
b    2
c    3
dtype: int64

In [5]:
s1.index

Index(['a', 'b', 'c'], dtype='object')

In [6]:
s1[1]

C:\Users\Admin\AppData\Local\Temp\ipykernel_3220\371843902.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[1]

np.int64(2)

In [7]:
s1['b']

np.int64(2)

In [8]:
s1.iloc[1]

np.int64(2)

In [9]:
df_0

              Name            Team  Number Position   Age
0    Avery Bradley  Boston Celtics     0.0       PG  25.0
1     John Holland  Boston Celtics    30.0       SG  27.0
2    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
3    Jordan Mickey  Boston Celtics     NaN       PF  21.0
4     Terry Rozier  Boston Celtics    12.0       PG  22.0
5  Jared Sullinger  Boston Celtics     7.0        C   NaN
6      Evan Turner  Boston Celtics    11.0       SG  27.0

In [10]:
df_0['Name']

0      Avery Bradley
1       John Holland
2      Jonas Jerebko
3      Jordan Mickey
4       Terry Rozier
5    Jared Sullinger
6        Evan Turner
Name: Name, dtype: object

In [11]:
df_0.Number

0     0.0
1    30.0
2     8.0
3     NaN
4    12.0
5     7.0
6    11.0
Name: Number, dtype: float64

In [12]:
df_0.index = list('abdcefg')
df_0

              Name            Team  Number Position   Age
a    Avery Bradley  Boston Celtics     0.0       PG  25.0
b     John Holland  Boston Celtics    30.0       SG  27.0
d    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
c    Jordan Mickey  Boston Celtics     NaN       PF  21.0
e     Terry Rozier  Boston Celtics    12.0       PG  22.0
f  Jared Sullinger  Boston Celtics     7.0        C   NaN
g      Evan Turner  Boston Celtics    11.0       SG  27.0

In [13]:
df_0[['Name','Team']]

              Name            Team
a    Avery Bradley  Boston Celtics
b     John Holland  Boston Celtics
d    Jonas Jerebko  Boston Celtics
c    Jordan Mickey  Boston Celtics
e     Terry Rozier  Boston Celtics
f  Jared Sullinger  Boston Celtics
g      Evan Turner  Boston Celtics

In [14]:
df_0

              Name            Team  Number Position   Age
a    Avery Bradley  Boston Celtics     0.0       PG  25.0
b     John Holland  Boston Celtics    30.0       SG  27.0
d    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
c    Jordan Mickey  Boston Celtics     NaN       PF  21.0
e     Terry Rozier  Boston Celtics    12.0       PG  22.0
f  Jared Sullinger  Boston Celtics     7.0        C   NaN
g      Evan Turner  Boston Celtics    11.0       SG  27.0

In [15]:
df_0.loc['a']

Name         Avery Bradley
Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Name: a, dtype: object

In [16]:
df_0.iloc[1]

Name          John Holland
Team        Boston Celtics
Number                30.0
Position                SG
Age                   27.0
Name: b, dtype: object

In [17]:
df_0.iloc[:2]

            Name            Team  Number Position   Age
a  Avery Bradley  Boston Celtics     0.0       PG  25.0
b   John Holland  Boston Celtics    30.0       SG  27.0

In [18]:
df_0.loc['a':'b']

            Name            Team  Number Position   Age
a  Avery Bradley  Boston Celtics     0.0       PG  25.0
b   John Holland  Boston Celtics    30.0       SG  27.0

In [19]:
df_0

              Name            Team  Number Position   Age
a    Avery Bradley  Boston Celtics     0.0       PG  25.0
b     John Holland  Boston Celtics    30.0       SG  27.0
d    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
c    Jordan Mickey  Boston Celtics     NaN       PF  21.0
e     Terry Rozier  Boston Celtics    12.0       PG  22.0
f  Jared Sullinger  Boston Celtics     7.0        C   NaN
g      Evan Turner  Boston Celtics    11.0       SG  27.0

In [20]:
df_0['Number'].loc["c"]

np.float64(nan)

In [21]:
df_0.iloc[2,3]

'PF'

In [22]:
df_0['Age']<25

a    False
b    False
d    False
c     True
e     True
f    False
g    False
Name: Age, dtype: bool

In [23]:
df_0[df_0['Age']<25]

            Name            Team  Number Position   Age
c  Jordan Mickey  Boston Celtics     NaN       PF  21.0
e   Terry Rozier  Boston Celtics    12.0       PG  22.0

In [24]:
import seaborn as sns

In [25]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [26]:
titanic = sns.load_dataset('titanic')
titanic.head() #default = 5

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [27]:
survive_number = titanic['survived']
survive_rate = survive_number.mean()
survive_rate

np.float64(0.3838383838383838)

In [28]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [29]:
male = titanic[titanic['sex'] == "male"]
female = titanic[titanic['sex'] == 'female']

print(male['survived'].mean())
print(female['survived'].mean())

0.18890814558058924
0.7420382165605095

In [30]:
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Score': [88, 76, 95, 65, 70],
    'Days_Off': [2, 5, 1, 8, 6]
}
df_lab1 = pd.DataFrame(data)
df_lab1

  Employee  Score  Days_Off
0    Alice     88         2
1      Bob     76         5
2  Charlie     95         1
3    David     65         8
4      Eva     70         6

In [31]:
df_lab1['Score'].rank()

0    4.0
1    3.0
2    5.0
3    1.0
4    2.0
Name: Score, dtype: float64