## Lesson 2: Loading, Diagnosing, Handling Missing Data, and Combining Datasets

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ntlong-NEU/DSEB65A-DataPre-Visual/refs/heads/main/Data/OnlineRetail.csv")

In [3]:
df.head() #default = 5

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [5]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  203422.000000  203422.000000  150039.000000
mean        9.585684       4.877820   15240.234832
std       240.921315     113.686676    1717.658493
min    -74215.000000       0.000000   12346.000000
25%         1.000000       1.250000   13791.000000
50%         3.000000       2.100000   15061.000000
75%        10.000000       4.130000   16771.000000
max     74215.000000   38970.000000   18287.000000

In [6]:
int('NaN')

ValueError: invalid literal for int() with base 10: 'NaN'

In [ ]:
int('123.0')

ValueError: invalid literal for int() with base 10: '123.0'

In [7]:
df['CustomerID'].astype('int')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [8]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  datetime64[ns]
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 12.4+ MB

In [9]:
df.isnull()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
203417,False,False,False,False,False,False,False,False
203418,False,False,False,False,False,False,False,False
203419,False,False,False,False,False,False,False,False
203420,False,False,False,False,False,False,False,False
203421,False,False,False,False,False,False,False,False

In [10]:
df.isnull().sum()

InvoiceNo          0
StockCode          0
Description      799
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     53383
Country            0
dtype: int64

In [11]:
df.isna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
203417,False,False,False,False,False,False,False,False
203418,False,False,False,False,False,False,False,False
203419,False,False,False,False,False,False,False,False
203420,False,False,False,False,False,False,False,False
203421,False,False,False,False,False,False,False,False

In [12]:
df.isna().sum()

InvoiceNo          0
StockCode          0
Description      799
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     53383
Country            0
dtype: int64

In [13]:
df.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 10.3+ MB

In [14]:
df.dropna(subset=['Description']).info()

<class 'pandas.core.frame.DataFrame'>
Index: 202623 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    202623 non-null  object
 1   StockCode    202623 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     202623 non-null  int64
 4   InvoiceDate  202623 non-null  datetime64[ns]
 5   UnitPrice    202623 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      202623 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 13.9+ MB

In [15]:
df_cus = df.dropna(subset=['CustomerID'])
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 10.3+ MB

In [16]:
df_cus['CustomerID'] = df_cus['CustomerID'].astype(int).astype(str)

C:\Users\Admin\AppData\Local\Temp\ipykernel_7676\3942897569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cus['CustomerID'] = df_cus['CustomerID'].astype(int).astype(str)

In [17]:
df_cus.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313,United Kingdom

In [18]:
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  object
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 10.3+ MB

In [19]:
df_cus.describe()

            Quantity                    InvoiceDate      UnitPrice
count  150039.000000                         150039  150039.000000
mean       12.527296  2011-04-06 06:42:14.911323392       3.884802
min    -74215.000000            2011-01-04 10:00:00       0.000000
25%         2.000000            2011-02-22 17:13:00       1.250000
50%         6.000000            2011-04-07 09:28:00       1.950000
75%        12.000000            2011-05-19 16:31:00       3.750000
max     74215.000000            2011-06-30 20:08:00   38970.000000
std       275.131638                            NaN     108.443379

In [20]:
df_cus = df.dropna(subset=['CustomerID'])
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 10.3+ MB

In [21]:
df.duplicated().sum()

np.int64(1512)

In [23]:
df_cus.duplicated().sum()

np.int64(1490)

In [24]:
df_cus.drop_duplicates(inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_7676\1705883601.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cus.drop_duplicates(inplace=True)

In [26]:
url1 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv'
url2 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv'
url3 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv'

pop = pd.read_csv(url1)
areas = pd.read_csv(url2)
abbrevs = pd.read_csv(url3)

In [27]:
pop.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [28]:
areas.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [29]:
abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [50]:
df01 = pd.merge(abbrevs,pop,
         left_on='abbreviation',
         right_on='state/region',
         how='outer')

In [51]:
df01.head()

    state abbreviation state/region     ages  year  population
0  Alaska           AK           AK    total  1990    553290.0
1  Alaska           AK           AK  under18  1990    177502.0
2  Alaska           AK           AK    total  1992    588736.0
3  Alaska           AK           AK  under18  1991    182180.0
4  Alaska           AK           AK  under18  1992    184878.0

In [55]:
df02 = pd.merge(df01,areas)[['state', 'ages','year', 'population','area (sq. mi)']]
df02.head()

    state     ages  year  population  area (sq. mi)
0  Alaska    total  1990    553290.0         656425
1  Alaska  under18  1990    177502.0         656425
2  Alaska    total  1992    588736.0         656425
3  Alaska  under18  1991    182180.0         656425
4  Alaska  under18  1992    184878.0         656425

In [59]:
df02.rename(columns={'area (sq. mi)':'area'}, inplace=True)
df02.head()

    state     ages  year  population    area
0  Alaska    total  1990    553290.0  656425
1  Alaska  under18  1990    177502.0  656425
2  Alaska    total  1992    588736.0  656425
3  Alaska  under18  1991    182180.0  656425
4  Alaska  under18  1992    184878.0  656425

In [61]:
df02['density'] = df02['population']/df02['area']
df02.head()

    state     ages  year  population    area   density
0  Alaska    total  1990    553290.0  656425  0.842884
1  Alaska  under18  1990    177502.0  656425  0.270407
2  Alaska    total  1992    588736.0  656425  0.896882
3  Alaska  under18  1991    182180.0  656425  0.277534
4  Alaska  under18  1992    184878.0  656425  0.281644

In [65]:
df03 = df02[(df02['ages']=='total')&(df02['year']==2010)].sort_values(by = 'density', ascending=False)

In [69]:
df03['Rank'] = df03['density'].rank(method='first',ascending=False )
df03.sort_values(by="Rank").head()

                     state   ages  year  population   area      density  Rank
341   District of Columbia  total  2010    605125.0     68  8898.897059   1.0
1493            New Jersey  total  2010   8802707.0   8722  1009.253268   2.0
1914          Rhode Island  total  2010   1052669.0   1545   681.339159   3.0
293            Connecticut  total  2010   3579210.0   5544   645.600649   4.0
954          Massachusetts  total  2010   6563263.0  10555   621.815538   5.0