## Lesson 2: Loading, Diagnosing, Handling Missing Data, and Combining Datasets

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ntlong-NEU/DSEB65A-DataPre-Visual/refs/heads/main/Data/OnlineRetail.csv")

In [3]:
df.head() #default = 5

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [5]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  203422.000000  203422.000000  150039.000000
mean        9.585684       4.877820   15240.234832
std       240.921315     113.686676    1717.658493
min    -74215.000000       0.000000   12346.000000
25%         1.000000       1.250000   13791.000000
50%         3.000000       2.100000   15061.000000
75%        10.000000       4.130000   16771.000000
max     74215.000000   38970.000000   18287.000000

In [10]:
int('NaN')

ValueError: invalid literal for int() with base 10: 'NaN'

In [9]:
int('123.0')

ValueError: invalid literal for int() with base 10: '123.0'

In [7]:
df['CustomerID'].astype('int')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [11]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  datetime64[ns]
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 12.4+ MB

In [14]:
df.isnull()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
203417,False,False,False,False,False,False,False,False
203418,False,False,False,False,False,False,False,False
203419,False,False,False,False,False,False,False,False
203420,False,False,False,False,False,False,False,False
203421,False,False,False,False,False,False,False,False

In [16]:
df.isnull().sum()

InvoiceNo          0
StockCode          0
Description      799
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     53383
Country            0
dtype: int64

In [17]:
df.isna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
203417,False,False,False,False,False,False,False,False
203418,False,False,False,False,False,False,False,False
203419,False,False,False,False,False,False,False,False
203420,False,False,False,False,False,False,False,False
203421,False,False,False,False,False,False,False,False

In [20]:
df.isna().sum()

InvoiceNo          0
StockCode          0
Description      799
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     53383
Country            0
dtype: int64

In [21]:
df.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 10.3+ MB

In [23]:
df.dropna(subset=['Description']).info()

<class 'pandas.core.frame.DataFrame'>
Index: 202623 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    202623 non-null  object
 1   StockCode    202623 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     202623 non-null  int64
 4   InvoiceDate  202623 non-null  datetime64[ns]
 5   UnitPrice    202623 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      202623 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 13.9+ MB

In [24]:
df_cus = df.dropna(subset=['CustomerID'])
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 10.3+ MB

In [26]:
df_cus['CustomerID'] = df_cus['CustomerID'].astype(int).astype(str)

C:\Users\Admin\AppData\Local\Temp\ipykernel_16644\3942897569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cus['CustomerID'] = df_cus['CustomerID'].astype(int).astype(str)

In [27]:
df_cus.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313,United Kingdom

In [28]:
df_cus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  object
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 10.3+ MB

In [29]:
df_cus.describe()

            Quantity                    InvoiceDate      UnitPrice
count  150039.000000                         150039  150039.000000
mean       12.527296  2011-04-06 06:42:14.911323392       3.884802
min    -74215.000000            2011-01-04 10:00:00       0.000000
25%         2.000000            2011-02-22 17:13:00       1.250000
50%         6.000000            2011-04-07 09:28:00       1.950000
75%        12.000000            2011-05-19 16:31:00       3.750000
max     74215.000000            2011-06-30 20:08:00   38970.000000
std       275.131638                            NaN     108.443379